# Generated by Django 6.0.2 on 2026-03-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='specialization',
            new_name='specializations',
        ),
    ]
