# Generated by Django 6.0.2 on 2026-03-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_specialization_guide_specializations'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Guide Assigned')], default='PENDING', max_length=20),
        ),
    ]
