# Generated by Django 6.0.2 on 2026-03-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_guide_email_guide_phone_student_email_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Unknown Student', max_length=100),
            preserve_default=False,
        ),
    ]
